[package]
name = "rst"
version = "0.1.0"
authors = ["Samvel Abrahamyan <=>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uinput = "0.1.3"
uinput-sys = "0.1.7"
libc = "0.2.73"
ioctl-rs = "0.2"
libudev = "0.2.0"